### ISSUE TITLE
"pix_url is deprecated" warning

### ISSUE THREAD

**Issue by thepurpleblob** [davosmith/moodle-block_checklist#4]
Line https://github.com/davosmith/moodle-block_checklist/blob/master/block_checklist.php#L351

"pix_url is deprecated. Use image_url for images pix_icon for icons"

**Comment by davosmith** [comment]
Looks like a simple issue to fix - are you able to send me a pull request to fix it? (and I can approve it quickly)

Otherwise I will try to look at it in a couple of weeks time when I'm back from holiday (assuming I don't forget).

**Comment by thepurpleblob** [comment]
I'll see what I can do. Things are a bit mad today. Just logging it before I forgot.

**Comment by davosmith** [comment]
Should now be fixed.
