### ISSUE TITLE
[Trivial] "Unbalanced" percentage evaluation

### ISSUE THREAD

**Issue by scara** [davosmith/moodle-block_checklist#5]
On "troubleshooting" an error [described in the Italian Community](https://moodle.org/mod/forum/discuss.php?d=396624) I found that the percentage is evaluated against float 100 and integer 100 in https://github.com/davosmith/moodle-block_checklist/blob/61baac90214eb823f978f717ab353300c0588295/block_checklist.php#L299 and https://github.com/davosmith/moodle-block_checklist/blob/61baac90214eb823f978f717ab353300c0588295/block_checklist.php#L346 respectively.

It looks like using `100.0` in both parts would be better.
Besides I'm wondering why `print_user_progressbar()` should evaluate the percentage by its own instead of using that being defined in the `$checklist` object.

Thoughts?

HTH,
Matteo

**Comment by davosmith** [comment]
I find it hard to imagine a situation in which this would make any actual difference, but, for completeness, I've fixed it.

As for why it doesn't use the percent value inside the checklist object - I suspect that the code that added the percent item to the checklist object was written later, so it may not have been available for use. I wrote the code 5 years ago - I can't remember really.

I am not going to change to using the value inside the checklist object, as the code is complex enough that I'd be risking introducing a bug, in case there is a code path that gets there without it being present.
